# Copyright 2012 Extesla Digital Entertainment, Ltd.. All rights reserved.
#
# It is illegal to use, reproduce or distribute any part of this
# Intellectual Property without prior written authorization from
# Extesla Digital Entertainment, Ltd..
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network "private_network", ip: "1.0.0.0"
  # config.vm.network :forwarded_port, guest: 80, guest_ip: "1.0.0.0", host: 80, host_ip: "127.0.0.1"

  config.vm.synced_folder "wwwroot/", "/srv/vagrant/data"
  config.vm.synced_folder "logs/", "/srv/vagrant/logs"

  config.vm.provider :virtualbox do |vb|
    vb.name      = "lorecall"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  config.vm.provision :puppet do |puppet|
	puppet.manifests_path = "tools/Puppet/manifests"
	puppet.module_path = ".puppet/modules"

	puppet.options = ["--verbose"]
	puppet.manifest_file  = "default.pp"
  end

end
